databases:
  - name: smash_note_db
    databaseName: smash_note_db
    user: django_user
    region: singapore
    plan: free

services:
  - type: web
    name: smash_note
    env: python
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn smash_proj.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smash_note_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true