from django.core.management.base import BaseCommand
from smash_note.models import Character

class Command(BaseCommand):
    help = 'Creates all character data in the database'

    def handle(self, *args, **options):
        characters = [
            {"character_name":"マリオ","image_url":"images/mario.jpg"},
            {"character_name":"ドンキーコング","image_url":"images/donkey.jpg"},
            {"character_name":"リンク","image_url":"images/link.jpg"},
            {"character_name":"サムス","image_url":"images/samus.jpg"},
            {"character_name":"ダークサムス","image_url":"images/dark_samus.jpg"},
            {"character_name":"ヨッシー","image_url":"images/yoshi.jpg"},
            {"character_name":"カービー","image_url":"images/kirby.jpg"},
            {"character_name":"フォックス","image_url":"images/fox.jpg"},
            {"character_name":"ピカチュウ","image_url":"images/pikachu.jpg"},
            {"character_name":"ルイージ","image_url":"images/luigi.jpg"},
            {"character_name":"ネス","image_url":"images/ness.jpg"},
            {"character_name":"CF","image_url":"images/captain_falcon.jpg"},
            {"character_name":"プリン","image_url":"images/purin.jpg"},
            {"character_name":"ピーチ","image_url":"images/peach.jpg"},
            {"character_name":"デイジー","image_url":"images/daisy.jpg"},
            {"character_name":"クッパ","image_url":"images/koopa.jpg"},
            {"character_name":"アイスクライマー","image_url":"images/ice_climber.jpg"},
            {"character_name":"シーク","image_url":"images/sheik.jpg"},
            {"character_name":"ゼルダ","image_url":"images/zelda.jpg"},
            {"character_name":"ドクターマリオ","image_url":"images/drmario.jpg"},
            {"character_name":"ピチュー","image_url":"images/pichu.jpg"},
            {"character_name":"ファルコ","image_url":"images/falco.jpg"},
            {"character_name":"マルス","image_url":"images/marth.jpg"},
            {"character_name":"ルキナ","image_url":"images/lucina.jpg"},
            {"character_name":"こどもリンク","image_url":"images/young_link.jpg"},
            {"character_name":"ガノンドロフ","image_url":"images/ganondorf.jpg"},
            {"character_name":"ミューツー","image_url":"images/mewtwo.jpg"},
            {"character_name":"ロイ","image_url":"images/roy.jpg"},
            {"character_name":"クロム","image_url":"images/chrom.jpg"},
            {"character_name":"ゲーム＆ウォッチ","image_url":"images/game_and_watch.jpg"},
            {"character_name":"メタナイト","image_url":"images/meta_knight.jpg"},
            {"character_name":"ピット","image_url":"images/pit.jpg"},
            {"character_name":"ブラックピット","image_url":"images/black_pit.jpg"},
            {"character_name":"ゼロスーツサムス","image_url":"images/zero_suit_samus.jpg"},
            {"character_name":"ワリオ","image_url":"images/wario.jpg"},
            {"character_name":"スネーク","image_url":"images/snake.jpg"},
            {"character_name":"アイク","image_url":"images/ike.jpg"},
            {"character_name":"ポケトレ","image_url":"images/pokemon_trainer.jpg"},
            {"character_name":"ディディコング","image_url":"images/dd.jpg"},
            {"character_name":"ルカ","image_url":"images/lucas.jpg"},
            {"character_name":"ソニック","image_url":"images/sonic.jpg"},
            {"character_name":"デデデ","image_url":"images/ddd.jpg"},
            {"character_name":"ピクオリ","image_url":"images/pikumin_and_orimar.jpg"},
            {"character_name":"ルカリオ","image_url":"images/lucario.jpg"},
            {"character_name":"ロボット","image_url":"images/robot.jpg"},
            {"character_name":"トゥーンリンク","image_url":"images/toon_link.jpg"},
            {"character_name":"ウルフ","image_url":"images/wolf.jpg"},
            {"character_name":"村人","image_url":"images/murabito.jpg"},
            {"character_name":"ロックマン","image_url":"images/rockman.jpg"},
            {"character_name":"フィットレ","image_url":"images/fit_trainer.jpg"},
            {"character_name":"ロゼチコ","image_url":"images/rose_chiko.jpg"},
            {"character_name":"リトルマック","image_url":"images/little_mac.jpg"},
            {"character_name":"ゲッコウガ","image_url":"images/gekkouga.jpg"},
            {"character_name":"パルテナ","image_url":"images/palutena.jpg"},
            {"character_name":"パックマン","image_url":"images/pac_man.jpg"},
            {"character_name":"ルフレ","image_url":"images/reflet.jpg"},
            {"character_name":"シュルク","image_url":"images/shulk.jpg"},
            {"character_name":"クッパジュニア","image_url":"images/koopa_jr.jpg"},
            {"character_name":"ダックハント","image_url":"images/duck_hunt.jpg"},
            {"character_name":"リュウ","image_url":"images/ryu.jpg"},
            {"character_name":"ケン","image_url":"images/ken.jpg"},
            {"character_name":"クラウド","image_url":"images/cloud.jpg"},
            {"character_name":"カムイ","image_url":"images/kamui.jpg"},
            {"character_name":"ベヨネッタ","image_url":"images/bayonetta.jpg"},
            {"character_name":"インクリング","image_url":"images/inkling.jpg"},
            {"character_name":"リドリー","image_url":"images/ridley.jpg"},
            {"character_name":"シモン","image_url":"images/simon.jpg"},
            {"character_name":"リヒター","image_url":"images/richter.jpg"},
            {"character_name":"キングクルール","image_url":"images/king_k_rool.jpg"},
            {"character_name":"しずえ","image_url":"images/shizue.jpg"},
            {"character_name":"ガオガエン","image_url":"images/gaogaen.jpg"},
            {"character_name":"パックンフラワー","image_url":"images/packun_flower.jpg"},
            {"character_name":"ジョーカー","image_url":"images/joker.jpg"},
            {"character_name":"勇者","image_url":"images/hero.jpg"},
            {"character_name":"バンカズ","image_url":"images/bankazu.jpg"},
            {"character_name":"テリー","image_url":"images/terry.jpg"},
            {"character_name":"ベレス","image_url":"images/byleth.jpg"},
            {"character_name":"メンメン","image_url":"images/minmin.jpg"},
            {"character_name":"スティーブ","image_url":"images/steve.jpg"},
            {"character_name":"セフィロス","image_url":"images/sephiroth.jpg"},
            {"character_name":"ホムヒカ","image_url":"images/homuhika.jpg"},
            {"character_name":"カズヤ","image_url":"images/kazuya.jpg"},
            {"character_name":"ソラ","image_url":"images/sora.jpg"},
            {"character_name":"格闘mii","image_url":"images/mii_brawler.jpg"},
            {"character_name":"剣術mii","image_url":"images/mii_sword.jpg"},
            {"character_name":"射撃mii","image_url":"images/mii_gunner.jpg"},
        ]

        for data in characters:
            character = Character(**data)
            character.save()

        self.stdout.write(self.style.SUCCESS('this command Success'))